name: Deploy DotNet project to function app with a Linux environment

on:
  #workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: AzureFunction  # set this to your application's name
  OUTPUT_FOLDER": '.'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.x'              # set this to the dotnet version to use
  PACKAGE_NAME: AzureFunction
  OCTOPUS_PROJECT_NAME: AzureFunction
  OCTOPUS_SPACE_NAME: Default
  ENVIRONMENT_NAME: Dev
  CHANNEL_NAME: DevChannel

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.1.1
      with:
        version: latest

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.OUTPUT_FOLDER }}'
        dotnet build --configuration Release --output ./output
        dotnet publish --output bin\Release\PublishOutput --configuration Release
        cd bin\Release\PublishOutput
        octo pack --id=AzureFunction --format=zip --outputFolder=./dist --version="${env:GITHUB_RUN_NUMBER}"
        popd

    - name: Handoff to Octopus
      env:
        OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      run:
        #cd bin\Release\PublishOutput
        #octo pack --id=AzureFunction --format=zip --outputFolder=./dist --version="${env:GITHUB_RUN_NUMBER}"
        octo push --package="/binReleasePublishOutput/AzureFunction${env:GITHUB_RUN_NUMBER}" --server="${env:OCTOPUS_URL}" --apiKey="${env:OCTOPUS_API_KEY}"
        octo create-release --project="${env:OCTOPUS_PROJECT_NAME}" --packageVersion="${env:GITHUB_RUN_NUMBER}" --releaseNumber="${env:env:GITHUB_RUN_NUMBER}" --server="${env:OCTOPUS_URL}" --apiKey="${env:OCTOPUS_API_KEY}" --space="${env:OCTOPUS_SPACE_NAME}" --deployTo="${env:ENVIRONMENT_NAME}" --channel="${env:CHANNEL_NAME}" --variable="Feature Branch Name:${env:ENVIRONMENT_NAME}" --variable="Merged Branch Name:${env:ENVIRONMENT_NAME}"
